BEGIN TRANSACTION;
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (1,'36642293000158', 'AF Invest Cri FII Recebiveis Imobiliarios', 'Papel', 'Fundo', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (2,'29641226000153', 'CSHG Renda Urbana-FI Imobiliario-FII', 'Varejo', 'Fundo', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (3,'08706065000169', 'FI Imobiliario - FII Hotel Maxinvest', 'Hotéis', 'Fundo', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (4,'28830325000110', 'FI Imobiliario Iridium Recebiveis Imobiliarios', 'Papel', 'Fundo', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (5,'13873457000152', 'FI Imob Rio Bravo Renda Educacional - FII - Unica', 'Educacional', 'Fundo', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (6,'15576907000170', 'FII Rio Bravo Renda Varejo-FII', 'Agências / Varejo', 'Fundo', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (7,'28548288000152', 'TRX Real Estate FII Closed Fund', 'Varejo', 'Fundo', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (8,'28757546000100', 'XP Malls Fundo de Investimento Imobiliario', 'Shopping', 'Fundo', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (9,'26499833000132', 'Malls Brasil Plural FI Imobiliario', 'Shopping', 'Fundo', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (10,'09346601000125', 'B3 SA Brasil Bolsa Balcao', 'Serviços Financeiros', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (11,'17344597000194', 'BB Seguridade Participacoes SA', 'Seguradora', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (12,'92702067000196', 'Banco do Estado do Rio Grande do Sul B Pref Shs', 'Banco', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (13,'14110585000107', 'Meliuz SA', 'Programas e Serviços', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (14,'92012467000170', 'Grazziotin SA Preference Shares', 'Varejo', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (15,'56643018000166', 'Eucatex SA Industria e Comercio Preference Shares', 'Commodities', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (16,'33376989000191', 'IRB Brasil Resseguros SA', 'Seguradora', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (17,'61532644000115', 'Itausa SA Preference Shares', 'Serviços Financeiros', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (18,'03378521000175', 'Light SA', 'Elétrica', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (19,'21314559000166', 'Movida Participacoes SA', 'Aluguel de Carros', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (20,'76484013000145', 'Companhia de Saneamento Parana SANEPAR Unit', 'Saneamento', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (21,'08801621000186', 'SYN prop e tech SA', 'Exploração de Imóveis', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (22,'07859971000130', 'Transmissora Alianca Energia Eletrica SA', 'Elétrica', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (23,'02998611000104', 'CTEEP Cia Transm Energia Eletr Paulista Preference Shares', 'Elétrica', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (24,'60894730000105', 'Usinas Siderurgicas de Mins Grs SA USMNS', 'Commodities', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (25,'02558157000162', 'Telefonica Brasil SA', 'Telecomunicações', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (26,'00000000000191', 'Banco do Brasil SA', 'Banco', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (27,'90400888000142', 'Banco Santander Brasil SA', 'Banco', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (28,'35864448000138', 'FII KINEA SC', 'Papel', 'Fundo', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (29,'16671412000193', 'FII SDI Rio Bravo Renda Logistica', 'Logístico', 'Fundo', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (30,'89637490000145', 'Klabin', 'Commodities', 'CiaAberta', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (31,'22219335000138', 'Banestes Recebíveis Imobiliarios', 'Papel', 'Fundo', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (32,'36501128000186', 'Fundo de Investimento Riza Terrax', 'Terras', 'Fundo', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (33,'11839593000109', 'BTG Pactual Logistica', 'Logístico', 'Fundo', 1);
INSERT INTO empresas ('id','cnpj', 'razao_social', 'setor_atividade', 'tipo_empresa', 'ativo') VALUES (34,'33592510000154', 'Vale S.A.', 'Commodities', 'CiaAberta', 1);



INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (1, 1, 'AFHI11', 'FII','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (2, 2, 'HGRU11', 'FII','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (3, 3, 'HTMX11', 'FII','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (4, 4, 'IRDM11', 'FII','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (5, 5, 'RBED11', 'FII','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (6, 6, 'RBVA11', 'FII','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (7, 7, 'TRXF11', 'FII','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (8, 8, 'XPML11', 'FII','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (9, 9, 'MALL11', 'FII','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (10, 10, 'B3SA3', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (11, 11, 'BBSE3', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (12, 12, 'BRSR6', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (13, 13, 'CASH3', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (14, 14, 'CGRA4', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (15, 15, 'EUCA4', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (16, 16, 'IRBR3', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (17, 17, 'ITSA4', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (18, 18, 'LIGT3', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (19, 19, 'MOVI3', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (20, 20, 'SAPR11', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (21, 21, 'SYNE3', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (22, 22, 'TAEE3', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (23, 23, 'TRPL4', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (24, 24, 'USIM3', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (25, 25, 'VIVT3', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (26, 26, 'BBAS3', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (27, 27, 'SANB3', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (28, 28, 'KNCR11', 'FII','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (29, 29, 'SDIL11', 'FII','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (30, 30, 'KLBN3', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (31, 31, 'BCRI11', 'FII','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (32, 32, 'RZTR11', 'FII','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (33, 33, 'BTLG11', 'FII','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (34, 34, 'VALE3', 'Acao','', 1);
INSERT INTO ativos ('id', 'empresa_id', 'ticker', 'classe', 'nome', 'ativo') VALUES (35, 20, 'SAPR4', 'Acao','', 1);

INSERT INTO corretoras ('id', 'nome', 'descricao', 'ativo') VALUES (1, 'BANCO INTER S/A', 'INTER', 1);
INSERT INTO corretoras ('id', 'nome', 'descricao', 'ativo') VALUES (2, 'XP INVESTIMENTOS CCTVM S/A', 'CLEAR', 1);
INSERT INTO corretoras ('id', 'nome', 'descricao', 'ativo') VALUES (3, 'AGORA CTVM S/A', 'AGORA', 1);
INSERT INTO corretoras ('id', 'nome', 'descricao', 'ativo') VALUES (4, 'BRADESCO S/A CTVM', 'BRADESCO', 1);
INSERT INTO corretoras ('id', 'nome', 'descricao', 'ativo') VALUES (5, 'NU INVEST CORRETORA DE VALORES S.A.', 'EASY INVEST', 1);



INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (1, 'ativo', 1, 'criacao', '', NULL, 'AFHI11', datetime('now'), "Ativo 'AFHI11' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (2, 'ativo', 2, 'criacao', '', NULL, 'HGRU11', datetime('now'), "Ativo 'HGRU11' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (3, 'ativo', 3, 'criacao', '', NULL, 'HTMX11', datetime('now'), "Ativo 'HTMX11' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (4, 'ativo', 4, 'criacao', '', NULL, 'IRDM11', datetime('now'), "Ativo 'IRDM11' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (5, 'ativo', 5, 'criacao', '', NULL, 'RBED11', datetime('now'), "Ativo 'RBED11' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (6, 'ativo', 6, 'criacao', '', NULL, 'RBVA11', datetime('now'), "Ativo 'RBVA11' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (7, 'ativo', 7, 'criacao', '', NULL, 'TRXF11', datetime('now'), "Ativo 'TRXF11' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (8, 'ativo', 8, 'criacao', '', NULL, 'XPML11', datetime('now'), "Ativo 'XPML11' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (9, 'ativo', 9, 'criacao', '', NULL, 'MALL11', datetime('now'), "Ativo 'MALL11' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (10, 'ativo', 10, 'criacao', '', NULL, 'B3SA3', datetime('now'), "Ativo 'B3SA3' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (11, 'ativo', 11, 'criacao', '', NULL, 'BBSE3', datetime('now'), "Ativo 'BBSE3' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (12, 'ativo', 12, 'criacao', '', NULL, 'BRSR6', datetime('now'), "Ativo 'BRSR6' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (13, 'ativo', 13, 'criacao', '', NULL, 'CASH3', datetime('now'), "Ativo 'CASH3' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (14, 'ativo', 14, 'criacao', '', NULL, 'CGRA4', datetime('now'), "Ativo 'CGRA4' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (15, 'ativo', 15, 'criacao', '', NULL, 'EUCA4', datetime('now'), "Ativo 'EUCA4' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (16, 'ativo', 16, 'criacao', '', NULL, 'IRBR3', datetime('now'), "Ativo 'IRBR3' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (17, 'ativo', 17, 'criacao', '', NULL, 'ITSA4', datetime('now'), "Ativo 'ITSA4' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (18, 'ativo', 18, 'criacao', '', NULL, 'LIGT3', datetime('now'), "Ativo 'LIGT3' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (19, 'ativo', 19, 'criacao', '', NULL, 'MOVI3', datetime('now'), "Ativo 'MOVI3' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (20, 'ativo', 20, 'criacao', '', NULL, 'SAPR11', datetime('now'), "Ativo 'SAPR11' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (21, 'ativo', 21, 'criacao', '', NULL, 'SYNE3', datetime('now'), "Ativo 'SYNE3' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (22, 'ativo', 22, 'criacao', '', NULL, 'TAEE3', datetime('now'), "Ativo 'TAEE3' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (23, 'ativo', 23, 'criacao', '', NULL, 'TRPL4', datetime('now'), "Ativo 'TRPL4' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (24, 'ativo', 24, 'criacao', '', NULL, 'USIM3', datetime('now'), "Ativo 'USIM3' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (25, 'ativo', 25, 'criacao', '', NULL, 'VIVT3', datetime('now'), "Ativo 'VIVT3' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (26, 'ativo', 26, 'criacao', '', NULL, 'BBAS3', datetime('now'), "Ativo 'BBAS3' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (27, 'ativo', 27, 'criacao', '', NULL, 'SANB3', datetime('now'), "Ativo 'SANB3' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (28, 'ativo', 28, 'criacao', '', NULL, 'KNCR11', datetime('now'), "Ativo 'KNCR11' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (29, 'ativo', 29, 'criacao', '', NULL, 'SDIL11', datetime('now'), "Ativo 'SDIL11' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (30, 'ativo', 30, 'criacao', '', NULL, 'KLBN3', datetime('now'), "Ativo 'KLBN3' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (31, 'ativo', 31, 'criacao', '', NULL, 'BCRI11', datetime('now'), "Ativo 'BCRI11' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (32, 'ativo', 32, 'criacao', '', NULL, 'RZTR11', datetime('now'), "Ativo 'RZTR11' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (33, 'ativo', 33, 'criacao', '', NULL, 'BTLG11', datetime('now'), "Ativo 'BTLG11' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (34, 'ativo', 34, 'criacao', '', NULL, 'VALE3', datetime('now'), "Ativo 'VALE3' criado.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (35, 'ativo', 35, 'criacao', '', NULL, 'SAPR4', datetime('now'), "Ativo 'SAPR4' criado.", 1);

INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (36, 'corretora', 1, 'criacao', 'INTER DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA', NULL, NULL, datetime('now'), "Corretora 'INTER criada.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (37, 'corretora', 1, 'alteracao', 'BANCO INTER S/A', NULL, NULL, datetime('now'), "Corretora 'INTER' alterada.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (38, 'corretora', 2, 'criacao', 'CLEAR CORRETORA - GRUPO XP', NULL, NULL, datetime('now'), "Corretora 'CLEAR criada.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (39, 'corretora', 2, 'alteracao', 'XP INVESTIMENTOS CORRETORA DE CAMBIO TITULOS E VALORES MOBILIARIOS S/A', NULL, NULL, datetime('now'), "Corretora 'CLEAR alterada.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (40, 'corretora', 2, 'alteracao', 'XP INVESTIMENTOS CCTVM S/A', NULL, NULL, datetime('now'), "Corretora 'CLEAR alterada.", 1);


INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (41, 'corretora', 3, 'criacao', 'AGORA CTVM S/A', NULL, NULL, datetime('now'), "Corretora 'AGORA' criada.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (42, 'corretora', 4, 'criacao', 'BRADESCO S/A CTVM', NULL, NULL, datetime('now'), "Corretora 'BRADESCO' criada.", 1);
INSERT INTO eventos ('id', 'tipo', 'entidade_id', 'evento', 'nome', 'ticker_antigo', 'ticker_novo', 'data_ex', 'observacoes', 'ativo') VALUES (43, 'corretora', 5, 'criacao', 'NU INVEST CORRETORA DE VALORES S.A.', NULL, NULL, datetime('now'), "Corretora 'EASY INVEST' criada.", 1);

COMMIT;
