BEGIN TRANSACTION;
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('36642293000158', 'AF Invest Cri FII Recebiveis Imobiliarios', 'Papel', 'Fundo', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('29641226000153', 'CSHG Renda Urbana-FI Imobiliario-FII', 'Varejo', 'Fundo', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('08706065000169', 'FI Imobiliario - FII Hotel Maxinvest', 'Hotéis', 'Fundo', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('28830325000110', 'FI Imobiliario Iridium Recebiveis Imobiliarios', 'Papel', 'Fundo', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('13873457000152', 'FI Imob Rio Bravo Renda Educacional - FII - Unica', 'Educacional', 'Fundo', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('15576907000170', 'FII Rio Bravo Renda Varejo-FII', 'Agências / Varejo', 'Fundo', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('28548288000152', 'TRX Real Estate FII Closed Fund', 'Varejo', 'Fundo', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('28757546000100', 'XP Malls Fundo de Investimento Imobiliario', 'Shopping', 'Fundo', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('26499833000132', 'Malls Brasil Plural FI Imobiliario', 'Shopping', 'Fundo', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('09346601000125', 'B3 SA Brasil Bolsa Balcao', 'Serviços Financeiros', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('17344597000194', 'BB Seguridade Participacoes SA', 'Seguradora', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('92702067000196', 'Banco do Estado do Rio Grande do Sul B Pref Shs', 'Banco', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('14110585000107', 'Meliuz SA', 'Programas e Serviços', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('92012467000170', 'Grazziotin SA Preference Shares', 'Tecidos. Vestuário e Calçados', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('56643018000166', 'Eucatex SA Industria e Comercio Preference Shares', 'Materiais Básicos', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('33376989000191', 'IRB Brasil Resseguros SA', 'Seguradora', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('61532644000115', 'Itausa SA Preference Shares', 'Serviços Financeiros', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('03378521000175', 'Light SA', 'Elétrica', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('21314559000166', 'Movida Participacoes SA', 'Aluguel de Carros', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('76484013000145', 'Companhia de Saneamento Parana SANEPAR Unit', 'Saneamento', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('08801621000186', 'SYN prop e tech SA', 'Exploração de Imóveis', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('07859971000130', 'Transmissora Alianca Energia Eletrica SA', 'Elétrica', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('02998611000104', 'CTEEP Cia Transm Energia Eletr Paulista Preference Shares', 'Elétrica', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('60894730000105', 'Usinas Siderurgicas de Mins Grs SA USMNS', 'Materiais Básicos', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('02558157000162', 'Telefonica Brasil SA', 'Telecomunicações', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('00000000000191', 'Banco do Brasil SA', 'Banco', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('90400888000142', 'Banco Santander Brasil SA', 'Banco', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('35864448000138', 'FII KINEA SC', 'Papel', 'Fundo', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('16671412000193', 'FII SDI Rio Bravo Renda Logistica', 'Logístico', 'Fundo', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('89637490000145', 'Klabin', 'Materiais Básicos', 'CiaAberta', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('22219335000138', 'Banestes Recebíveis Imobiliarios', 'Papel', 'Fundo', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('36501128000186', 'Fundo de Investimento Riza Terrax', 'Terras', 'Fundo', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('11839593000109', 'BTG Pactual Logistica', 'Logístico', 'Fundo', 1);
INSERT INTO empresas ("cnpj", "razao_social", "setor_atividade", "tipo_empresa", "ativo") VALUES ('33592510000154', 'Vale S.A.', 'Mineração', 'CiaAberta', 1);
COMMIT;
